CONTRIBUTING.md
docs/extras/filters.md
docs/extras/styling.md
docs/index.md

Title says it all. Have a look to images in the [documentation](https://dsd-dbs.github.io/capellambse-context-diagrams/).

Fix image URLS

---

capellambse_context_diagrams/context.py
docs/gen_images.py

Resolve request from closed [PR](https://github.com/DSD-DBS/capellambse-context-diagrams/pull/3#discussion_r918669302).

Fix filter setting

---

capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/context.py
pyproject.toml
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_interface_diagrams.py

Fixed collection and styling of interface context diagrams for SystemComponentExchanges. This PR relies on [PR #142](https://github.com/DSD-DBS/py-capellambse/pull/142) of capellambse.

Fix SA interface context

---

capellambse_context_diagrams/collectors/portless.py

Title.
Don't mind the pipeline. This is waiting for [PR#165](https://github.com/DSD-DBS/py-capellambse/pull/165) on py-capellambse.

feat: Add missing exchanges in collection

---

.github/CODEOWNERS

ci: Add viktor to wildcard in CODEOWNERS

---

.github/workflows/build-test-publish.yml

ci: Update git actions

---

pyproject.toml

Add least version [v0.5.9 for capellambse](https://github.com/DSD-DBS/py-capellambse/releases/tag/v0.5.9).

fix: Add least version in `pyproject.toml`

---

capellambse_context_diagrams/serializers.py

Added reference point of center box to hierarchical junctions.

fix(serializers): Fix position of hierarchical junctions

---

docs/index.md

fix(docs): Fix hierarchical diagram SVG

---

capellambse_context_diagrams/context.py

Hidden elements shouldn't appear in nodes.

fix(context): Fix diagram nodes

---

.pre-commit-config.yaml
capellambse_context_diagrams/context.py

Add a missing attribute to the ContextDiagram class.

Fix allow render

---

capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/context.py
tests/test_context_diagrams.py
tests/test_filters.py
tests/test_interface_diagrams.py

Issue #45 describes the filter bug for `InterfaceContextDiagram`. These commits fix this issue and add some tests for stability.

Fix interface filters

---

docs/quickstart.md

fix(docs): Add hints for node/npm dependency

---

.pre-commit-config.yaml
capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/class_tree.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella

Include properties from `super` with a generalization, saving on the amount of edges.

feat(class-tree): Extend class tree diagram

---

.pre-commit-config.yaml
capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/collectors/realization_view.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
docs/gen_images.py
docs/realization_view.md
mkdocs.yml
tests/data/ContextDiagram.afm
tests/data/ContextDiagram.capella
tests/test_realization_views.py

**_This depends on [py-capellambse #369](https://github.com/DSD-DBS/py-capellambse/pull/369)_**

feat(realization-view): Add realization view diagram

---

capellambse_context_diagrams/collectors/tree_view.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella

The converse direction of generalizations wasn't recognized at all. This commit fixes it.

fix(tree-view): Add `sub` classes to tree

---

.pre-commit-config.yaml
capellambse_context_diagrams/collectors/dataflow_view.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/generic.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/collectors/portless.py
capellambse_context_diagrams/collectors/realization_view.py
capellambse_context_diagrams/collectors/tree_view.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/filters.py
capellambse_context_diagrams/serializers.py
docs/data_flow_view.md
docs/gen_images.py
mkdocs.yml
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_dataflow_views.py
tests/test_filters.py
tests/test_labels.py

Don't mind the commit history with the first wip commit. I squash all commits into one anyways.
Since this commit has impact on all diagram types, it was needed to implement tests and document the data flow diagram type. This was still missing.
**_Depends on [py-capellambse #389](https://github.com/DSD-DBS/py-capellambse/pull/389)._**

Add label wrapping

---

capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/serializers.py

**_Depends on [py-capellambse #402](https://github.com/DSD-DBS/py-capellambse/pull/402)._**

Fix-label-issues

---

capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
docs/gen_images.py
docs/realization_view.md
docs/tree_view.md
tests/test_realization_views.py

- Added `layer_sizing` option `INDIVIDUAL`.
- Also set default `layer_sizing` to `WIDTH` for best
layout.
_Ignore the wip commit, I squash them both into one before merging anyways!_
_**Depends on [py-capellambse #413](https://github.com/DSD-DBS/py-capellambse/pull/413)**_

Fix-realization-view

---

capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/context.py
docs/data_flow_view.md
docs/gen_images.py
docs/index.md
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_interface_diagrams.py

- Support nested components
_**Depends on  [py-capellambse #418](https://github.com/DSD-DBS/py-capellambse/pull/418)**_

Feat nested comps

---

capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/collectors/default.py
docs/gen_images.py
docs/index.md
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

Fix physical components

---

capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/context.py
docs/gen_images.py
docs/index.md
docs/interface.md
mkdocs.yml
tests/test_interface_diagrams.py

Add interface section and document `hide_functions`.

feat: Feat-hide-functions

---

capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/exchanges.py

This improves the straightening of the interface in the interface context diagram.

feat: Change to `NETWORK_SIMPLEX` placement and add edge straightening to interfaces

---

capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/collectors/cable_tree.py
capellambse_context_diagrams/context.py
docs/cable_tree.md
docs/gen_images.py
mkdocs.yml
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_cable_tree_views.py

feat: Implement Cable Tree View

---

capellambse_context_diagrams/__init__.py

Depends on [py-capellambse #459](https://github.com/DSD-DBS/py-capellambse/pull/459)

feat: Add LAB and SAB support for `PhysicalLink` interface context

---

capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/errors.py

fix: Raise an exception when left and right are the same

---

capellambse_context_diagrams/collectors/cable_tree.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/context.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_cable_tree_views.py

fix: Fix Cable Tree View for sub-component links

---

src/capellambse_context_diagrams/collectors/realization_view.py
src/capellambse_context_diagrams/context.py

Use the attributes set on the Diagram class
instead from the empty params.

fix(realization-view): No parents visible bugfix

---

src/capellambse_context_diagrams/collectors/tree_view.py
src/capellambse_context_diagrams/context.py

Instead use the attributes set on the Diagram
class.

refactor(tree-view): Don't use params in collector

---

src/capellambse_context_diagrams/collectors/generic.py
src/capellambse_context_diagrams/collectors/portless.py

fix: Move edges to the correct owner

---

src/capellambse_context_diagrams/_elkjs.py

If deno isn't available locally, the elkjs manager instance tries to download and use a runtime with the exact version of context-diagrams. This works fine while sitting exactly on a release tag, but for all other cases, setuptools-scm will generate intermediate version numbers like `1.0.1.dev5+ABCD123`. These obviously do not correspond to releases on Github, nor do they exist as binaries on disk, which is why context-diagrams would always fail to spawn the layouting server.
This commit changes the version detection logic to step back to the latest release tag if such an intermediate dev version was generated.

Download last full release during X.devY versions

---

src/capellambse_context_diagrams/_elkjs.py

The server is currently single-threaded anyway, so firing off multiple requests in parallel would not result in any speedups. On the other hand however, it would result in race conditions (potentially starting multiple servers, or mixing up responses between multiple reads).

Guard interactions with the ELK server behind a lock

---

docs/gen_images.py
docs/index.md
src/capellambse_context_diagrams/builders/default.py
src/capellambse_context_diagrams/context.py
src/capellambse_context_diagrams/enums.py
tests/conftest.py
tests/data/elk_input/context_diagrams/blackbox_physical_context_diagram_with_int_cycles.json
tests/data/elk_input/context_diagrams/blackbox_physical_context_diagram_without_int_relations.json
tests/data/elk_layout/context_diagrams/blackbox_physical_context_diagram_with_int_cycles.json
tests/data/elk_layout/context_diagrams/blackbox_physical_context_diagram_without_int_relations.json
tests/test_context_diagrams.py

With this feature the user is finally able to restore the original blackbox view which was the only offered view mode for Context Diagrams in the past.
Appropriate documentation has been added too.

fix: Fix blackbox mode

---

src/capellambse_context_diagrams/builders/interface.py
src/capellambse_context_diagrams/context.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/data/elk_input/interface_context/interface_hidden_functions_nested_component_context_diagram.json
tests/data/elk_layout/interface_context/interface_hidden_functions_nested_component_context_diagram.json
tests/test_interface_diagrams.py

Components can be nested and in that case `self.left` or `self.right` can't be resolved when the `hide_functions` flag is enabled.

fix(interface): Find nested components when function hidden

---

tests/conftest.py
tests/test_cable_tree_views.py
tests/test_dataflow_views.py
tests/test_interface_diagrams.py
tests/test_realization_views.py

No need for setting the default values anymore.

test: Fix default render params

---

docs/extras/styling.md
docs/gen_images.py
src/capellambse_context_diagrams/context.py
src/capellambse_context_diagrams/helpers.py
src/capellambse_context_diagrams/serializers.py
src/capellambse_context_diagrams/styling.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/data/elk_input/context_diagrams/pvmt_styling_context_diagram.json
tests/data/elk_input/context_diagrams/pvmt_styling_with_children_coloring_context_diagram.json
tests/data/elk_layout/context_diagrams/pvmt_styling_context_diagram.json
tests/data/elk_layout/context_diagrams/pvmt_styling_with_children_coloring_context_diagram.json
tests/test_context_diagrams.py

**_This PR depends on DSD-DBS/py-capellambse#549._**

feat: Get individual stylings from PVMT

---

pyproject.toml
src/capellambse_context_diagrams/collectors/_generic.py
src/capellambse_context_diagrams/context.py

**_Depends on dbinfrago/py-capellambse#586._**

feat: Support `context_groups` render parameter
