dbinfrago/capellambse-context-diagrams

README.md

Pypi is not capable to resolve relative URLs. Now we are using the raw githubusercontent URLs.

Fix image URLs

---

capellambse_context_diagrams/collectors/__init__.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/generic.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/serializers.py
tests/test_context_diagrams.py

All space-checker methods were removed by using `aird.Diagram`'s own viewport calculation functionality and a hidden implicit box sizing feature of ELK. In the latter children or labels with sizes (width and height information) make any size information on the parent useless. We used this behaviour to get enough space for big labels in boxes such that adjustments aren't needed anymore. Since we are not patching any sizes of diagram elements anymore we don't risk overlaps anymore. Kudos to @Wuestengecko.

Use `aird.Diagram`'s `.calculate_viewport`

---

tests/test_context_diagrams.py

This fixes broken Python3.9 windows workflow.

Reduce minimum size for py3.9-windows test

---

capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/portless.py

The `.exchanges` attribute was renamed to `.related_exchanges` in v.0.5.1 of py-capellambse.

Fix exchange collection for portless diagrams

---

capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/generic.py
capellambse_context_diagrams/serializers.py
docs/gen_images.py
docs/index.md
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

Hierarchy support and handling:
Identified a bug: False direction for `ComponentExchanges` when changing direction of ports. Direction needs to be checked and patched against direction of ports.

feat: Add hierarchy recognition and handling to diagrams with ports

---

capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/context.py
docs/index.md
pyproject.toml
tests/test_context_diagrams.py

This change makes hierarchy in context diagrams disabled per default. This can now be set via the new `include_inner_objects = True` flag. Also a new, faster way of rendering context diagrams has been implemented:
```
render_params = {"include_inner_objects": True}
obj.context_diagram.render("svgdiagram", **render_params).save_drawing()
```

Feature enable hierarchy and make ContextDiagram callable

---

capellambse_context_diagrams/context.py
docs/realization_view.md
tests/test_realization_views.py

feat(realization-view): Add `layer_sizing` render parameter

---

CONTRIBUTING.md
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/realization_view.py
capellambse_context_diagrams/context.py
docs/extras/filters.md
docs/extras/styling.md
docs/index.md
docs/realization_view.md
docs/tree_view.md
tests/test_realization_views.py

Render context diagrams with symbols with `display_symbols_as_boxes` per default.
**_Depends on [py-capellambse #372](https://github.com/DSD-DBS/py-capellambse/pull/372)._**

Fix context diagrams

---

capellambse_context_diagrams/collectors/tree_view.py
capellambse_context_diagrams/serializers.py
docs/tree_view.md
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_tree_views.py

Added more render parameters and fixed the displayed direction of `Generalization` edges.
With the depth parameter the recursion is ended after the first iteration already which speeds up the computation immensely. A whole tree is still computed per default. The generalizations are now disabled on all other nodes than root per default. The original behavior can be set via `super|sub="ALL"`.

Fix tree view

---

capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py

This moves the centerbox into its parent box if it is in the context. Also other boxes are moved into the parent box if the parent-child relation holds.
**_This PR depends on [py-capellambse #381](https://github.com/DSD-DBS/py-capellambse/pull/381)._**

feat(context-diagrams): Add `display_parent_relation` feature

---

capellambse_context_diagrams/_elkjs.py

If we cannot create the cache directory to install the elk.js dependencies, we used to crash with whatever error message the OS gave us. This can sometimes be misleading, e.g. when the message is talking about missing permissions, but in reality `$HOME` or `$XDG_CACHE_HOME` is simply set to a broken value.
This commit catches an OSError here and instead shows a nicer error message (and also much more concise stack trace) with a concrete hint towards `$HOME`.
This is mostly relevant when running inside a container or as a system service, as it's much easier to accidentally miss some envvars there.

Show nicer error if cachedir can't be created

---

capellambse_context_diagrams/__init__.py

In one of our container builds, we want to explicitly preinstall the needed Node modules at build time. This significantly improves the render time of the first context diagram after container startup, as otherwise the modules would have to be installed during startup / first render.
This PR adds a small public helper function, which simply forwards to the private module that actually does the work.

Add a helper to install elk.js ahead of time

---

capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/collectors/tree_view.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
docs/extras/derived.md
docs/gen_images.py
mkdocs.yml
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

Feat derived interfaces

---

.github/workflows/lint.yml
capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/dataflow_view.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/generic.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/collectors/portless.py
capellambse_context_diagrams/collectors/realization_view.py
capellambse_context_diagrams/collectors/tree_view.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
pyproject.toml
tests/__init__.py
tests/test_labels.py

refactor: Change _elkjs typed dicts to pydantic elements

---

capellambse_context_diagrams/collectors/dataflow_view.py
docs/realization_view.md

Refactor Dataflow View

---

capellambse_context_diagrams/collectors/generic.py

Common UUID was detected as the target and source itself. This commit fixes it by just removing this UUID from both sets.

fix(context): Handle cycles in `move_edges`

---

capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
tests/test_context_diagrams.py

This PR is for fixing minor bugs which occured due to the many PRs that have been merged.

fix(realization-view): Fix broken styleclass for edges

---

capellambse_context_diagrams/collectors/default.py
docs/index.md

AT root system function wouldn't render and we forgot something in docs

fix: Fix bug for root elements

---

capellambse_context_diagrams/filters.py
docs/gen_images.py
tests/test_filters.py

Rename FEX_EX_ITEMS to SHOW_EX_ITEMS and FEX_OR_EX_ITEMS to EXCH_OR_EX_ITEMS, and extend them to work both with FunctionalExchange and ComponentExchange.

Extend (and rename) FEX_EX_ITEMS and FEX_OR_EX_ITEMS

---

capellambse_context_diagrams/collectors/exchanges.py

This didn't work and wasn't necessary.

fix(context-diagram): Remove interface direction correction

---

pyproject.toml

This should make transitioning to v0.6.x a bit smoother.

Constrain capellambse to v0.5.x

---

capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/generic.py
capellambse_context_diagrams/collectors/tree_view.py

Closes #125
- edges between target and the same element now all have the same direction
- tree-view fix other kinds of associations
- satisfy mypy

fix: Apply edge direction correction

---

.pre-commit-config.yaml
capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/dataflow_view.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/generic.py
capellambse_context_diagrams/collectors/makers.py
capellambse_context_diagrams/collectors/portless.py
capellambse_context_diagrams/collectors/realization_view.py
capellambse_context_diagrams/collectors/tree_view.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/filters.py
capellambse_context_diagrams/serializers.py
capellambse_context_diagrams/styling.py
docs/gen_ref_pages.py
pyproject.toml
tests/__init__.py
tests/test_capability_diagrams.py
tests/test_filters.py
tests/test_labels.py

This PR migrates the codebase to the new import structure and changed class names in capellambse v0.6.x.
The diff is a bit inflated, as I also took the opportunity to unify the imports, and also repair the mypy hook (so I could rely on it during the migration). The latter uncovered a variety of type errors, which I then also went ahead and fixed. I didn't touch any of the logic (as far as I could), so there shouldn't be any breakage.
I've marked the commit as breaking change, to try and make downstream more aware of this upgrade.

Upgrade to capellambse v0.6.x

---

capellambse_context_diagrams/_elkjs.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/context.py
capellambse_context_diagrams/serializers.py
docs/extras/styling.md
docs/gen_images.py
tests/test_filters.py

Labels appear twice but that's an issue with the renderer in pycapellambse (fixed in https://github.com/DSD-DBS/py-capellambse/pull/453)

Feat port label

---

capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/collectors/tree_view.py

Improve logging formatting, and reduce some warnings about modelling issues down to debug level.
This helps reduce noise, especially during CI runs that generate context diagrams as part of it (e.g. when rendering some documents out of the model).

Improve logging

---

pyproject.toml

The wheel used to also include the documentation, which unhelpfully got installed into `.../site-packages/docs`. This commit fixes that by changing the package declaration for setuptools: instead of excluding what we don't want, we now include explicitly only the actual code packages. This still makes use of setuptools' discovery to find the individual submodules of capellambse_context_diagrams, but it won't try to find code anywhere else.

Only include code in the wheel

---

capellambse_context_diagrams/collectors/tree_view.py

Simplified the association resolving significantly, thanks to the capellambse API. Extended the `Class` processing to now also handle the case when no `Association` was modelled even tho a separate `Class` was used for the `Property`.

feat(tree-view): Add handling of properties w/o `Association`s

---

.pre-commit-config.yaml
capellambse_context_diagrams/collectors/exchanges.py
capellambse_context_diagrams/context.py
tests/test_context_diagrams.py

First stepping stone for a save detection of changes to context-diagrams. This will be used for solving https://github.com/DSD-DBS/capella-polarion/issues/71.

Feat-cache-collection

---

capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/collectors/generic.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

Cycles would end up in duplicated exchanges and faulty movement to the owner box.

feat(context-diagram): Add cycle detection

---

capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/context.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

- ´display_unused_ports´ to toggle unused ports
- on ´display_port_labels´ box height is adjusted
TODO:

feat: Add unused ports flag and port label height calculation

---

capellambse_context_diagrams/__init__.py
capellambse_context_diagrams/collectors/default.py
capellambse_context_diagrams/context.py
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

Also fix bugs:
- False symbols bug
- Correctly calculate the centerbox size
Solves #162

fix!(context-diagram): Enable derived interfaces per default on `Component`s`

---

src/capellambse_context_diagrams/collectors/exchanges.py

When outgoing and incoming edges are the same, the direction shouldn't be reversed.

fix: Port spread not correct for equal case

---

docs/extras/derived.md
pyproject.toml
src/capellambse_context_diagrams/__init__.py
src/capellambse_context_diagrams/collectors/__init__.py
src/capellambse_context_diagrams/collectors/custom.py
src/capellambse_context_diagrams/collectors/dataflow_view.py
src/capellambse_context_diagrams/collectors/default.py
src/capellambse_context_diagrams/collectors/generic.py
src/capellambse_context_diagrams/collectors/makers.py
src/capellambse_context_diagrams/context.py
src/capellambse_context_diagrams/serializers.py
tests/data/ContextDiagram.aird
tests/data/ContextDiagram.capella
tests/test_context_diagrams.py

- collects target's children's context for context diagram (resolves #176)
- exchanges between context components are collected (display_actor_relation)
- blackbox view (resolves #177)
- fixes edge routing

refactor: Use custom collector for default context

---

pyproject.toml

We use ruff for sorting imports now, so this is no longer necessary

chore: Remove pyls-isort

---

tests/conftest.py
tests/test_cable_tree_views.py
tests/test_context_diagrams.py
tests/test_dataflow_views.py
tests/test_interface_diagrams.py
tests/test_realization_views.py
tests/test_tree_views.py

Rewrite ELK input comparison test helper to assert equality directly, instead of returning a bool that gets asserted later.
This gives pytest better insight into the asserted data, enabling it to perform its magic assertion rewrites and enrich the test output. As such, this is most noticable when increasing verbosity with invocations like `pytest -vv`.

Inline the assertion into the ELK comparison test helper

---

.pre-commit-config.yaml
pyproject.toml

When running type checks under pre-commit, the declared dependencies are normally installed using the default Python interpreter, so they must be compatible with it. Pydantic started supporting Python 3.13 with v2.8.0.
Bump the minimum supported version, and thus the version that we type-check against, to ensure compatibility with Python 3.13.

Bump minimum supported Pydantic version

---

pyproject.toml

capellambse's CI currently needs a compatible context-diagrams release (on PyPI) for some of the checks. v0.7.0 is compatible with the current context-diagrams version, so it's safe to simply extend the range.

Extend accepted capellambse version range to include v0.7.x

---

.github/workflows/build-test-publish.yml
docs/.readthedocs.yaml

New deno v2.3.7 doesn't work. The process can't be started. Sad dino.
@zusorio :t-rex:

ci: Fixate deno to v2.3.6

---

src/capellambse_context_diagrams/_elkjs.py
tests/test_elk.py

This fixes ResourceWarnings about unclosed files when terminating the helper process, for example during interpreter shutdown.
To verify, run the following command[^1]:
[^1]: The additional `python` flags are needed to make the warnings visible, as the `ResourceWarning` category is ignored by default.
```sh
python -Xtracemalloc -Xdev -Walways -c '__import__("capellambse").loadcli("ife-demo").by_uuid("dab8526e-cf3a-4c8a-8fa1-7df4aa281bcf").context_diagram.render("svg")'
```
On current master, you will see the following warnings:
```
/usr/lib/python3.13/subprocess.py:1140: ResourceWarning: subprocess 37807 is still running
_warn("subprocess %s is still running" % self.pid,
Object allocated at (most recent call last):
File ".../src/capellambse_context_diagrams/_elkjs.py", lineno 398 …
```

Properly clean up stdin/out/err handles of the elk.js helper
